"""Convert a binary file to a C/C++ byte array header.

Supports optional Zstd compression metadata. Generates a header with
the binary data as a const unsigned char array plus size constants.

Usage:
    python3 convert_binary_to_array.py <input_before_compression> <input_after_compression> <output_header> <ON|OFF>
"""
import argparse
import re
import sys
from pathlib import Path
from typing import Final

# Anything a C identifier cannot contain, so a header named 'foo-bar.h' still
# yields a usable array name.
_NON_IDENTIFIER: Final = re.compile(r"[^0-9A-Za-z_]")


def binary_to_c_array(
    bin_file: Path,
    array_name: str,
    size_before_compression: int,
    is_compressed: bool,
) -> str:
    """Read a binary file and generate a C array declaration string."""
    binary_data = bin_file.read_bytes()

    hex_array = ", ".join(f"0x{b:02x}" for b in binary_data)
    lines = [
        f"const unsigned char {array_name}[] = {{\n    {hex_array}\n}};",
        f"const size_t {array_name}_size = sizeof({array_name}); // {len(binary_data)}",
    ]

    if is_compressed:
        lines.append(
            f"const size_t {array_name}_size_uncompressed = {size_before_compression}; "
            f"// size of the data in bytes, once it has been uncompressed."
        )
    else:
        lines.append(
            f"const size_t {array_name}_size_uncompressed = {array_name}_size; "
            f"// same as raw buffer, because data is not compressed."
        )

    lines.append(
        f'const bool   {array_name}_isCompressed = {"true" if is_compressed else "false"};'
    )

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Convert a binary file to a C/C++ byte array header."
    )
    parser.add_argument("input_before_compression", type=Path)
    parser.add_argument("input_after_compression", type=Path)
    parser.add_argument("output_header", type=Path)
    parser.add_argument("compressed", choices=("ON", "OFF", "on", "off"))
    args = parser.parse_args()

    is_compressed = args.compressed.upper() == "ON"
    source: Path = (
        args.input_after_compression if is_compressed else args.input_before_compression
    )

    for path in {args.input_before_compression, source}:
        if not path.is_file():
            print(f"error: no such file: {path}", file=sys.stderr)
            return 1

    array_name = _NON_IDENTIFIER.sub("_", args.output_header.name)

    try:
        c_array = binary_to_c_array(
            source,
            array_name,
            args.input_before_compression.stat().st_size,
            is_compressed,
        )
        header = "// generated by convert_binary_to_array.py\n"
        if is_compressed:
            header += "// Data is compressed.\n"
        args.output_header.write_text(header + c_array, encoding="utf-8")
    except OSError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
